### ISSUE TITLE
Failed to load JSHint library if VSCode was installed as a Snap.

### ISSUE THREAD

**Issue by NatoBoram** [microsoft/vscode-jshint#71]
JSHint was properly installed.

```bash
jshint --version
jshint v2.10.2
```

Here's my installation of VSCode.

```bash
snap info code-insiders 
name:      code-insiders
summary:   Code editing. Redefined.
publisher: Visual Studio Code (vscode✓)
contact:   https://twitter.com/code
license:   unset
description: |
  Visual Studio Code is a lightweight but powerful source code editor which runs on your desktop and
  is available for **Linux**, **macOS** and **Windows**. It comes with built-in support for
  **JavaScript**, **TypeScript** and **Node.js** and has a rich ecosystem of extensions for other
  languages (such as **C++**, **C#**, **Java**, **Python**, **PHP**, **Go**) and runtimes (such as
  **.NET** and **Unity**).
  
  By downloading and using Visual Studio Code, you agree to the license terms
  (https://code.visualstudio.com/License/) and privacy statement
  (https://privacy.microsoft.com/en-us/privacystatement). Visual Studio Code automatically sends
  telemetry data and crash dumps to help us improve the product. If you would prefer not to have
  this data sent please go see
  https://code.visualstudio.com/docs/supporting/FAQ#_how-to-disable-crash-reporting to learn how to
  disable it.
  
  https://github.com/Microsoft/vscode
commands:
  - code-insiders
  - code-insiders.url-handler
snap-id:      vNVY8DiBL4e2Q8H3Xtsh71c8QSTaxBdp
tracking:     stable
refresh-date: yesterday at 18:52 EDT
channels:
  stable:    56f1b479 2019-04-09 (114) 132MB classic
  candidate: ↑                               
  beta:      ↑                               
  edge:      ↑                               
installed:   56f1b479            (114) 132MB classic
```

Here's my OS.

```yaml
OS: Ubuntu 18.04.2 LTS x86_64 
Kernel: 4.18.0-18-generic 
Uptime: 3 hours, 52 mins 
Packages: 1936 
Shell: bash 4.4.19 
Resolution: 1920x1080 
DE: Unity 
WM: GNOME Shell 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: vscode 
CPU: Intel i5-3570K (4) @ 3.800GHz 
GPU: NVIDIA GeForce GTX 660 Ti 
Memory: 3776MiB / 7920MiB 
```

I also reported it in https://github.com/Microsoft/vscode/issues/72042.
